### ISSUE TITLE
Doesn't work with sbt 0.13

### ISSUE THREAD

**Issue by tyoc213** [spring-projects/spring-loaded#38]
Hi there I'm on OSX and trying to run but when I start `sbt` I get

``` sbt
SBT_OPTS="-javaagent:/Users/tyoc213/Downloads/springloaded-1.1.4.jar -noverify -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=756M"
```

```
objc[1719]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_40.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_40.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
```

and when I run `container:start`

```
java.lang.NoClassDefFoundError: org/springsource/loaded/ri/ReflectiveInterceptor
Caused by: java.lang.ClassNotFoundException: org.springsource.loaded.ri.ReflectiveInterceptor
 FAILED org.eclipse.jetty.server.handler.ContextHandlerCollection@485bbfa4: java.lang.NoClassDefFoundError: org/springsource/loaded/ri/ReflectiveInterceptor
java.lang.NoClassDefFoundError: org/springsource/loaded/ri/ReflectiveInterceptor
Caused by: java.lang.ClassNotFoundException: org.springsource.loaded.ri.ReflectiveInterceptor
FAILED org.eclipse.jetty.server.Server@73da3f0: java.lang.NoClassDefFoundError: org/springsource/loaded/ri/ReflectiveInterceptor
java.lang.NoClassDefFoundError: org/springsource/loaded/ri/ReflectiveInterceptor
Caused by: java.lang.ClassNotFoundException: org.springsource.loaded.ri.ReflectiveInterceptor
```

If I go back to jdk1.7.0_25 it is the same

I also have tried https://github.com/spring-projects/spring-loaded/pull/13 with 1.3.3

But no luck...
